apiVersion: v1
kind: Service
metadata:
  name: clv-internal
  namespace: clv-360
  labels:
    app: clv-internal
    environment: ${ENVIRONMENT}
  annotations:
    cloud.google.com/backend-config: '{"default": "clv-backend-config"}'
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app: clv-internal
