apiVersion: v1
kind: Service
metadata:
  name: clv-loadbalancer
  namespace: clv-360
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/app-protocols: '{"https":"HTTPS","http":"HTTP"}'
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: https
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: clv-service
