apiVersion: v1
kind: Service
metadata:
  name: clv-monitoring
  namespace: clv-360
  labels:
    app: clv-monitoring
    component: metrics
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: prometheus
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: grafana
  selector:
    app: clv-monitoring
