data_processing_config:
  # Data processing parameters
  MIN_FREQUENCY: 1
  MIN_REVENUE: 0.0
  MIN_TRANSACTION_VALUE: 0.0
  OUTLIER_THRESHOLD: 3 # Number of IQRs for outlier detection

  # Query parameters
  PROJECT_ID: "logic-dna-240402"
  DATASET: "CLV"
  TABLE: "T_CLV"
  LIMIT: 1000000
  COHORT_MONTH: "2020-01-01"
  MIN_PURCHASE_DATE: "2020-01-01"
  MAX_PURCHASE_DATE: null # Defaults to current date if None
  INCLUDE_ONLINE: true
  INCLUDE_STORE: true
  MIN_LOYALTY_POINTS: 0
