data_processing_config:
  # data processing parameters
  min_frequency: 1
  min_revenue: 1
  min_transaction_value: 1
  outlier_threshold: 3 # number of iqrs for outlier detection

  # query parameters
  project_id: "logic-dna-240402"
  dataset: "CLV"
  table: "T_CLV"
  limit: 10000000
  cohort_month: "2019-02-01"
  min_purchase_date: "2020-01-01"
  max_purchase_date: "2024-12-31"
  include_online: true
  include_store: true
  min_loyalty_points: 0
