data_processing_config:
  # Data quality parameters
  min_frequency: 1
  min_revenue: 0.01
  min_transaction_value: 0.01
  outlier_threshold: 3

  # GCP BigQuery parameters
  project_id: "logic-dna-240402"
  dataset: "CLV"
  table: "T_CLV"
  limit: 10000000  # Adjust based on your data volume
  
  # Date parameters
  cohort_month: "2024-01-01"  # Update to your cohort start
  min_purchase_date: "2024-01-01"
  max_purchase_date: "2024-12-31"
  
  # Transaction filters
  include_online: true
  include_store: true
  min_loyalty_points: 0
