# Deployment Configuration Settings

# Environment Settings
environment: "development"
model_serving:
  endpoint: "localhost:8080"
  timeout: 30
  max_retries: 3

# GCP Deployment Settings
project_id: "logic-dna-240402"
region: "us-west1"  # or your preferred region

vertex_ai:
  endpoint_name: "clv-prediction-endpoint"
  machine_type: "n1-standard-4"
  min_replicas: 1
  max_replicas: 5
  
monitoring:
  enable_monitoring: true
  alert_email: "rford@bluemercury.com"
  metrics_frequency: 60  # seconds

security:
  service_account: "clv-dev-sa@logic-dna-240402.iam.gserviceaccount.com"
  service_account_key_path: "~/.gcp/credentials/clv-dev-sa-key.json"
  network: "default"
