# Pipeline Configuration Settings
pipeline:
  input:
    table: "customer_transactions"
    dataset: "clv_data"
    project: "your-project-id"
  output:
    bucket: "gs://your-bucket"
    prefix: "clv_predictions"
  processing:
    batch_size: 1000
    workers: 4
