site_name: CLV by Defactio
site_description: Customer Lifetime Value Prediction System Documentation
site_author: Rob Ford
repo_url: https://github.com/robandrewford/clv-defactio
repo_name: clv-defactio

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: materialx.emoji.twemoji
      emoji_generator: materialx.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Configuration: getting-started/configuration.md
      - Quick Start: getting-started/quickstart.md
  - User Guide:
      - Data Pipeline: user-guide/data-pipeline.md
      - Model Training: user-guide/model-training.md
      - Deployment: user-guide/deployment.md
  - API Reference:
      - Models: api-reference/models.md
      - Pipeline: api-reference/pipeline.md
      - Utils: api-reference/utils.md
  - Development:
      - Contributing: development/contributing.md
      - Testing: development/testing.md
      - CI/CD: development/cicd.md
